//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("5a563fad-40bf-4fc0-9eb0-fab33b7cc979")]
[assembly: AssemblyTitle("FlexSearch Api")]
[assembly: AssemblyDescription("FlexSearch Api")]
[assembly: AssemblyProduct("FlexSearch")]
[assembly: AssemblyCopyright("(c) Seemant Rajvanshi, 2013")]
[assembly: AssemblyVersion("0.4.0.0")]
[assembly: AssemblyFileVersion("0.4.0.0")]
[assembly: AssemblyDelaySign(false)]


