// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FlexSearch API Library")]
[assembly: AssemblyDescriptionAttribute("FlexSearch API Library")]
[assembly: AssemblyProductAttribute("FlexSearch")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2010 - 2016 - FlexSearch")]
[assembly: AssemblyFileVersionAttribute("0.8.0")]
[assembly: AssemblyVersionAttribute("0.8.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.8.0";
        internal const string InformationalVersion = "0.8.0";
    }
}
