// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FlexSearch Logging Library")]
[assembly: AssemblyDescriptionAttribute("FlexSearch Logging Library")]
[assembly: AssemblyProductAttribute("FlexSearch")]
[assembly: AssemblyCopyrightAttribute("(c) Seemant Rajvanshi, 2012 - 2014")]
[assembly: AssemblyFileVersionAttribute("0.24.0.0")]
[assembly: AssemblyVersionAttribute("0.24.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.24.0.0";
    }
}
