// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FlexSearch Logging Library")]
[assembly: AssemblyDescriptionAttribute("FlexSearch Logging Library")]
[assembly: AssemblyProductAttribute("FlexSearch")]
[assembly: AssemblyCopyrightAttribute("(c) Seemant Rajvanshi, 2012 - 2014")]
[assembly: AssemblyFileVersionAttribute("0.23.1.1")]
[assembly: AssemblyVersionAttribute("0.23.1.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.23.1.1";
    }
}
