/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;
//using System.ServiceModel;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace FlexSearch.Api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  [DataContract(Namespace="")]
  public partial class VoteResponse : TBase
  {
    private int _Term;
    private bool _VoteGranted;

    [DataMember]
    public int Term
    {
      get
      {
        return _Term;
      }
      set
      {
        __isset.Term = true;
        this._Term = value;
      }
    }

    [DataMember]
    public bool VoteGranted
    {
      get
      {
        return _VoteGranted;
      }
      set
      {
        __isset.VoteGranted = true;
        this._VoteGranted = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    [DataContract]
    public struct Isset {
      public bool Term;
      public bool VoteGranted;
    }

    public VoteResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Term = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              VoteGranted = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("VoteResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.Term) {
        field.Name = "Term";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Term);
        oprot.WriteFieldEnd();
      }
      if (__isset.VoteGranted) {
        field.Name = "VoteGranted";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(VoteGranted);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override bool Equals(object that) {
      var other = that as VoteResponse;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.Term == other.__isset.Term) && ((!__isset.Term) || (System.Object.Equals(Term, other.Term))))
        && ((__isset.VoteGranted == other.__isset.VoteGranted) && ((!__isset.VoteGranted) || (System.Object.Equals(VoteGranted, other.VoteGranted))));
    }

    public override int GetHashCode() {
      int hashcode = 0;
      unchecked {
        hashcode = (hashcode * 397) ^ (!__isset.Term ? 0 : (Term.GetHashCode()));
        hashcode = (hashcode * 397) ^ (!__isset.VoteGranted ? 0 : (VoteGranted.GetHashCode()));
      }
      return hashcode;
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("VoteResponse(");
      sb.Append("Term: ");
      sb.Append(Term);
      sb.Append(",VoteGranted: ");
      sb.Append(VoteGranted);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
