/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum FieldPostingsFormat
  {
    Direct = 1,
    Memory = 2,
    Bloom = 3,
    Pulsing = 4,
    Lucene_4_1 = 5,
  }
}
