/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum FieldDocValuesFormat
  {
    Direct = 1,
    Memory = 2,
    Lucene_4_9 = 3,
  }
}
