/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum FieldSimilarity
  {
    BM25 = 1,
    TDF = 2,
  }
}
