/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum FieldType
  {
    Int = 1,
    Double = 2,
    ExactText = 3,
    Text = 4,
    Highlight = 5,
    Bool = 6,
    Date = 7,
    DateTime = 8,
    Custom = 9,
    Stored = 10,
    Long = 11,
  }
}
