/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum IndexState
  {
    Opening = 1,
    Online = 2,
    Offline = 3,
    Closing = 4,
  }
}
