/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum JobStatus
  {
    Initializing = 1,
    Initialized = 2,
    InProgress = 3,
    Completed = 4,
    CompletedWithErrors = 5,
  }
}
