/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum MissingValueOption
  {
    ThrowError = 1,
    Default = 2,
    Ignore = 3,
  }
}
