/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.ServiceModel;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace FlexSearch.Api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  [DataContract(Namespace="")]
  public partial class Node : TBase
  {

    [DataMember(Order = 1)]
    public string NodeName { get; set; }

    [DataMember(Order = 2)]
    public string IpAddress { get; set; }

    [DataMember(Order = 3)]
    public int Port { get; set; }

    /// <summary>
    /// 
    /// <seealso cref="NodeRole"/>
    /// </summary>
    [DataMember(Order = 4)]
    public NodeRole NodeRole { get; set; }

    [DataMember(Order = 5)]
    public int Priority { get; set; }

    public Node() {
    }

    public Node(string NodeName, string IpAddress, int Port, NodeRole NodeRole, int Priority) : this() {
      this.NodeName = NodeName;
      this.IpAddress = IpAddress;
      this.Port = Port;
      this.NodeRole = NodeRole;
      this.Priority = Priority;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_NodeName = false;
      bool isset_IpAddress = false;
      bool isset_Port = false;
      bool isset_NodeRole = false;
      bool isset_Priority = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              NodeName = iprot.ReadString();
              isset_NodeName = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              IpAddress = iprot.ReadString();
              isset_IpAddress = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              Port = iprot.ReadI32();
              isset_Port = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              NodeRole = (NodeRole)iprot.ReadI32();
              isset_NodeRole = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              Priority = iprot.ReadI32();
              isset_Priority = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_NodeName)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_IpAddress)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_Port)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_NodeRole)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_Priority)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Node");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "NodeName";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(NodeName);
      oprot.WriteFieldEnd();
      field.Name = "IpAddress";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(IpAddress);
      oprot.WriteFieldEnd();
      field.Name = "Port";
      field.Type = TType.I32;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(Port);
      oprot.WriteFieldEnd();
      field.Name = "NodeRole";
      field.Type = TType.I32;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)NodeRole);
      oprot.WriteFieldEnd();
      field.Name = "Priority";
      field.Type = TType.I32;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(Priority);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override bool Equals(object that) {
      var other = that as Node;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(NodeName, other.NodeName)
        && System.Object.Equals(IpAddress, other.IpAddress)
        && System.Object.Equals(Port, other.Port)
        && System.Object.Equals(NodeRole, other.NodeRole)
        && System.Object.Equals(Priority, other.Priority);
    }

    public override int GetHashCode() {
      int hashcode = 0;
      unchecked {
        hashcode = (hashcode * 397) ^ ((NodeName.GetHashCode()));
        hashcode = (hashcode * 397) ^ ((IpAddress.GetHashCode()));
        hashcode = (hashcode * 397) ^ ((Port.GetHashCode()));
        hashcode = (hashcode * 397) ^ ((NodeRole.GetHashCode()));
        hashcode = (hashcode * 397) ^ ((Priority.GetHashCode()));
      }
      return hashcode;
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Node(");
      sb.Append("NodeName: ");
      sb.Append(NodeName);
      sb.Append(",IpAddress: ");
      sb.Append(IpAddress);
      sb.Append(",Port: ");
      sb.Append(Port);
      sb.Append(",NodeRole: ");
      sb.Append(NodeRole);
      sb.Append(",Priority: ");
      sb.Append(Priority);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
