/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum NodeRole
  {
    ClusterMaster = 1,
    ClusterSlave = 2,
    Index = 3,
    Query = 4,
    UnDefined = 5,
  }
}
