/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FlexSearch.Api
{
  public enum ScriptType
  {
    SearchProfileSelector = 1,
    CustomScoring = 2,
    ComputedField = 3,
  }
}
