/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.ServiceModel;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace FlexSearch.Api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  [DataContract(Namespace="")]
  public partial class Tokenizer : TBase
  {
    private Dictionary<string, string> _Parameters;

    [DataMember(Order = 1)]
    public string TokenizerName { get; set; }

    [DataMember(Order = 2)]
    public Dictionary<string, string> Parameters
    {
      get
      {
        return _Parameters;
      }
      set
      {
        __isset.Parameters = true;
        this._Parameters = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    [DataContract]
    public struct Isset {
      public bool Parameters;
    }

    public Tokenizer() {
    }

    public Tokenizer(string TokenizerName) : this() {
      this.TokenizerName = TokenizerName;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_TokenizerName = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              TokenizerName = iprot.ReadString();
              isset_TokenizerName = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                Parameters = new Dictionary<string, string>();
                TMap _map5 = iprot.ReadMapBegin();
                for( int _i6 = 0; _i6 < _map5.Count; ++_i6)
                {
                  string _key7;
                  string _val8;
                  _key7 = iprot.ReadString();
                  _val8 = iprot.ReadString();
                  Parameters[_key7] = _val8;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_TokenizerName)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Tokenizer");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "TokenizerName";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(TokenizerName);
      oprot.WriteFieldEnd();
      if (Parameters != null && __isset.Parameters) {
        field.Name = "Parameters";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.String, Parameters.Count));
          foreach (string _iter9 in Parameters.Keys)
          {
            oprot.WriteString(_iter9);
            oprot.WriteString(Parameters[_iter9]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override bool Equals(object that) {
      var other = that as Tokenizer;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(TokenizerName, other.TokenizerName)
        && ((__isset.Parameters == other.__isset.Parameters) && ((!__isset.Parameters) || (TCollections.Equals(Parameters, other.Parameters))));
    }

    public override int GetHashCode() {
      int hashcode = 0;
      unchecked {
        hashcode = (hashcode * 397) ^ ((TokenizerName.GetHashCode()));
        hashcode = (hashcode * 397) ^ (!__isset.Parameters ? 0 : (TCollections.GetHashCode(Parameters)));
      }
      return hashcode;
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Tokenizer(");
      sb.Append("TokenizerName: ");
      sb.Append(TokenizerName);
      sb.Append(",Parameters: ");
      sb.Append(Parameters);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
