//****************************************************************
//  Generated by:  ToTypeScriptD
//  Website:       http://github.com/ToTypeScriptD/ToTypeScriptD
//  Version:       v0.1.5081.42854 - SHA1:66c203d - Debug
//  Date:          15/06/2015 01:17:47 PM
//
//  Assemblies:
//    FlexSearch.Core.dll
//
//****************************************************************

declare module FlexSearch.Core {

    export interface AnalysisRequest {
        Text: string;
    }

    export interface Country {
        Id: string;
        CountryName: string;
        Exports: string;
        Imports: string;
        Independence: string;
        MilitaryExpenditure: string;
        NetMigration: string;
        Area: string;
        InternetUsers: string;
        LabourForce: string;
        Population: number;
        AgriProducts: string;
        AreaComparative: string;
        Background: string;
        Capital: string;
        Climate: string;
        Economy: string;
        GovernmentType: string;
        MemberOf: string;
        CountryCode: string;
        Nationality: string;
        Coordinates: string;
    }

    export interface CreateResponse {
        Id: string;
    }

    export interface CsvIndexingRequest {
        IndexName: string;
        HasHeaderRecord: boolean;
        Headers: string[];
        Path: string;
    }

    enum DirectoryType_Dto {
        Undefined,
        FileSystem,
        MemoryMapped,
        Ram
    }

    export interface Document_Dto {
        Fields: string[];
        Id: string;
        TimeStamp: number;
        IndexName: string;
        Highlights: string[];
        Score: number;
        Default: FlexSearch.Core.Document_Dto;
    }

    export interface Field_Dto {
        FieldName: string;
        Analyze: boolean;
        Index: boolean;
        Store: boolean;
        IndexAnalyzer: string;
        SearchAnalyzer: string;
        FieldType: FlexSearch.Core.FieldType_Dto;
        Similarity: FlexSearch.Core.FieldSimilarity_Dto;
        IndexOptions: FlexSearch.Core.FieldIndexOptions_Dto;
        TermVector: FlexSearch.Core.FieldTermVector_Dto;
        OmitNorms: boolean;
        ScriptName: string;
    }

    enum FieldIndexOptions_Dto {
        Undefined,
        DocsOnly,
        DocsAndFreqs,
        DocsAndFreqsAndPositions,
        DocsAndFreqsAndPositionsAndOffsets
    }

    enum FieldSimilarity_Dto {
        Undefined,
        BM25,
        TFIDF
    }

    enum FieldTermVector_Dto {
        Undefined,
        DoNotStoreTermVector,
        StoreTermVector,
        StoreTermVectorsWithPositions,
        StoreTermVectorsWithPositionsandOffsets
    }

    enum FieldType_Dto {
        Undefined,
        Int,
        Double,
        ExactText,
        Text,
        Highlight,
        Bool,
        Date,
        DateTime,
        Custom,
        Stored,
        Long
    }

    export interface HighlightOption_Dto {
        FragmentsToReturn: number;
        HighlightedFields: string[];
        PostTag: string;
        PreTag: string;
    }
    
    export interface IndexConfiguration_Dto {
        CommitTimeSeconds: number;
        CommitEveryNFlushes: number;
        CommitOnClose: boolean;
        AutoCommit: boolean;
        DirectoryType: FlexSearch.Core.DirectoryType_Dto;
        DefaultWriteLockTimeout: number;
        RamBufferSizeMb: number;
        MaxBufferedDocs: number;
        RefreshTimeMilliseconds: number;
        AutoRefresh: boolean;
        IndexVersion: FlexSearch.Core.IndexVersion_Dto;
        UseBloomFilterForId: boolean;
        DefaultFieldSimilarity: FlexSearch.Core.FieldSimilarity_Dto;
    }

    export interface IndexExistsResponse {
        Exists: boolean;
    }

    enum IndexVersion_Dto {
        Undefined,
        Lucene_4_x_x,
        Lucene_5_0_0
    }

    export interface Job {
        JobId: string;
        TotalItems: number;
        ProcessedItems: number;
        FailedItems: number;
        Status: FlexSearch.Core.JobStatus;
        Message: string;
    }

    enum JobStatus {
        Undefined,
        Initializing,
        Initialized,
        InProgress,
        Completed,
        CompletedWithErrors
    }

    export interface SearchQuery_Dto {
        QueryName: string;
        Columns: string[];
        Count: number;
        Highlights: FlexSearch.Core.HighlightOption_Dto;
        IndexName: string;
        OrderBy: string;
        CutOff: number;
        DistinctBy: string;
        Skip: number;
        QueryString: string;
        ReturnFlatResult: boolean;
        ReturnScore: boolean;
        SearchProfile: string;
        SearchProfileScript: string;
        OverrideProfileOptions: boolean;
        ReturnEmptyStringForNull: boolean;
    }

    export interface SearchResults {
        Documents: FlexSearch.Core.Document_Dto[];
        RecordsReturned: number;
        TotalAvailable: number;
    }

    export interface SqlIndexingRequest {
        IndexName: string;
        Query: string;
        ConnectionString: string;
        ForceCreate: boolean;
        CreateJob: boolean;
    }
}

declare module FlexSearch.DuplicateDetection {

    export interface DuplicateDetectionReportRequest {
        SourceFileName: string;
        ProfileName: string;
        IndexName: string;
        QueryString: string;
        CutOff: number;
    }

    export interface DuplicateDetectionRequest {
        SelectionQuery: string;
        DisplayName: string;
        ThreadCount: number;
        IndexName: string;
        ProfileName: string;
        MaxRecordsToScan: number;
    }

    interface Session {
        Id: string;
        SessionId: string;
        IndexName: string;
        ProfileName: string;
        JobStartTime: Date;
        JobEndTime: Date;
        SelectionQuery: string;
        DisplayFieldName: string;
        RecordsReturned: number;
        RecordsAvailable: number;
        ThreadCount: number;
    }

    export interface SourceRecord {
        SessionId: string;
        SourceId: string;
        SourceRecordId: string;
        SourceDisplayName: string;
        SourceStatus: string;
        TotalDupes: number;
    }

    export interface Stats {
        TotalRecords: number;
        MatchedRecords: number;
        NoMatchRecords: number;
        OneMatchRecord: number;
        TwoMatchRecord: number;
        MoreThanTwoMatchRecord: number;
    }

    export interface TargetRecord {
        TargetId: string;
        TargetRecordId: string;
        TargetDisplayName: string;
        Quality: string;
        TargetScore: number;
    }

}