/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.ServiceModel;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace FlexSearch.Api.Connector
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  [DataContract(Namespace="")]
  public partial class SqlQuery : TBase
  {

    [DataMember(Order = 1)]
    public string SingleSelectQuery { get; set; }

    [DataMember(Order = 2)]
    public string MultipleSelectQuery { get; set; }

    public SqlQuery() {
    }

    public SqlQuery(string SingleSelectQuery, string MultipleSelectQuery) : this() {
      this.SingleSelectQuery = SingleSelectQuery;
      this.MultipleSelectQuery = MultipleSelectQuery;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_SingleSelectQuery = false;
      bool isset_MultipleSelectQuery = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              SingleSelectQuery = iprot.ReadString();
              isset_SingleSelectQuery = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              MultipleSelectQuery = iprot.ReadString();
              isset_MultipleSelectQuery = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_SingleSelectQuery)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_MultipleSelectQuery)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SqlQuery");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "SingleSelectQuery";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(SingleSelectQuery);
      oprot.WriteFieldEnd();
      field.Name = "MultipleSelectQuery";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(MultipleSelectQuery);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override bool Equals(object that) {
      var other = that as SqlQuery;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(SingleSelectQuery, other.SingleSelectQuery)
        && System.Object.Equals(MultipleSelectQuery, other.MultipleSelectQuery);
    }

    public override int GetHashCode() {
      int hashcode = 0;
      unchecked {
        hashcode = (hashcode * 397) ^ ((SingleSelectQuery.GetHashCode()));
        hashcode = (hashcode * 397) ^ ((MultipleSelectQuery.GetHashCode()));
      }
      return hashcode;
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SqlQuery(");
      sb.Append("SingleSelectQuery: ");
      sb.Append(SingleSelectQuery);
      sb.Append(",MultipleSelectQuery: ");
      sb.Append(MultipleSelectQuery);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
