// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FlexSearch Server")]
[assembly: AssemblyDescriptionAttribute("FlexSearch Server")]
[assembly: AssemblyProductAttribute("FlexSearch")]
[assembly: AssemblyCopyrightAttribute("(c) Seemant Rajvanshi, 2012 - 2014")]
[assembly: AssemblyFileVersionAttribute("0.21.1.0")]
[assembly: AssemblyVersionAttribute("0.21.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.21.1.0";
    }
}
