// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FlexSearch Core Library")>]
[<assembly: AssemblyDescriptionAttribute("FlexSearch Core Library")>]
[<assembly: AssemblyProductAttribute("FlexSearch")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (C) 2010 - 2017 - FlexSearch")>]
[<assembly: AssemblyFileVersionAttribute("0.8.5")>]
[<assembly: AssemblyVersionAttribute("0.8.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FlexSearch Core Library"
    let [<Literal>] AssemblyDescription = "FlexSearch Core Library"
    let [<Literal>] AssemblyProduct = "FlexSearch"
    let [<Literal>] AssemblyCopyright = "Copyright (C) 2010 - 2017 - FlexSearch"
    let [<Literal>] AssemblyFileVersion = "0.8.5"
    let [<Literal>] AssemblyVersion = "0.8.5"
