// ----------------------------------------------------------------------------
//  Licensed to FlexSearch under one or more contributor license 
//  agreements. See the NOTICE file distributed with this work 
//  for additional information regarding copyright ownership. 
//
//  This source code is subject to terms and conditions of the 
//  Apache License, Version 2.0. A copy of the license can be 
//  found in the License.txt file at the root of this distribution. 
//  You may also obtain a copy of the License at:
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
//  By using this source code in any fashion, you are agreeing
//  to be bound by the terms of the Apache License, Version 2.0.
//
//  You must not remove this notice, or any other, from this software.
// ----------------------------------------------------------------------------
namespace FlexSearch.Core

open FlexSearch.Api
open FlexSearch.Api.Model
open FlexLucene.Document
open FlexLucene.Index
open FlexLucene.Search
open FlexLucene.Search.Highlight
open FlexSearch.Core
open System
open System.Collections.Generic
open System.Linq
open System.ComponentModel.Composition

type Variables = Dictionary<string, string>

/// Signifies the behaviour of the clause when no value
/// is provided for searching
type ClauseMatchRule = 
    /// Default behaviour that is to thrown error when no
    /// value is provided for searching
    | ThrowError = 0
    /// Convert the clause to a match all clause which allows
    /// matching against all values
    | All = 1
    /// Convert the clause to a match none clause which matches
    /// no values
    | None = 2
    /// Use the default value for the field for searching
    | FieldDefault = 3
    /// Use the user defined value to search
    | UseDefault = 4

type ClauseProperties = 
    { MatchRule : ClauseMatchRule
      Filter : bool
      DefaultValue : string option
      Boost : float32 option
      ConstantScore : float32 option
      Switches : IEnumerable<Switch> }
    static member Create(parameters : FunctionParameter list) = 
        let mutable matchRule = ClauseMatchRule.ThrowError
        let mutable defaultValue = None
        let mutable boost = None
        let mutable constantScore = None
        let mutable filter = false
        let switches = new List<Switch>()
        // Could use List.choose here but it is a lot slower
        for p in parameters do
            match p with
            | Switch(s) -> 
                match s.Name with
                | InvariantEqual "MatchAll" -> matchRule <- ClauseMatchRule.All
                | InvariantEqual "MatchNone" -> matchRule <- ClauseMatchRule.None
                | InvariantEqual "MatchFieldDefault" -> matchRule <- ClauseMatchRule.FieldDefault
                | InvariantEqual "UseDefault" -> 
                    match s.Value with
                    | Some v -> 
                        if isBlank v then matchRule <- ClauseMatchRule.FieldDefault
                        else 
                            matchRule <- ClauseMatchRule.UseDefault
                            defaultValue <- Some v
                    | None -> matchRule <- ClauseMatchRule.FieldDefault
                | InvariantEqual "Boost" -> 
                    match s.Value with
                    | Some v -> 
                        if isNotBlank v then 
                            let boostValue = pFloat 1.0f v
                            if boostValue <> 1.0f then boost <- Some boostValue
                    | None -> ()
                | InvariantEqual "ConstantScore" -> 
                    match s.Value with
                    | Some v -> 
                        if isNotBlank v then 
                            let constantValue = pFloat 1.0f v
                            if constantValue <> 1.0f then constantScore <- Some constantValue
                    | None -> ()
                | InvariantEqual "Filter" -> filter <- true
                | _ -> switches.Add(s)
            | _ -> ()
        { MatchRule = matchRule
          Filter = filter
          DefaultValue = defaultValue
          Boost = boost
          ConstantScore = constantScore
          Switches = switches }

/// Used to represent a search operator like allOf etc.
[<Interface>]
type IQueryFunction = 
    abstract GetQuery : FieldSchema * values:IEnumerable<string> * properties:ClauseProperties -> Result<Query>

type SearchBaggage = 
    { Fields : IReadOnlyDictionary<string, FieldSchema>
      QueryFunctions : Dictionary<string, IQueryFunction> }

/// This module is responsible for generating Lucene Queries from the AST
/// generated by the parser.
[<AutoOpen>]
module AstParser = 
    let inline queryNotFound queryName = QueryNotFound <| queryName
    let inline fieldNotFound fieldName = InvalidFieldName <| fieldName
    
    let getFieldSchema fieldName (fields : IReadOnlyDictionary<string, FieldSchema>) = 
        maybe { 
            let! field = fields |> keyExists2 (fieldName, fieldNotFound)
            do! FieldSchema.isSearchable field |> boolToResult (StoredFieldCannotBeSearched(field.FieldName))
            return field
        }
    
    // Gets a variable value from the search query.
    // Empty/blank values are considered an error
    let getVariable (name : VariableName) (variables : Variables) = 
        match variables.TryGetValue <| name.ToLower() with
        | true, value -> 
            if isNotBlank value then ok value
            else fail <| MissingVariableValue name
        | _ -> fail <| MissingVariableValue name
    
    /// Checks if there is a need to generate query or not? In case there are no tokens then
    /// the main query could be replaced with match all or match none queries.
    /// Also if the match rule is set to use defaults then we can inject the default value.
    let byPassMainQueryGeneration (fieldName, fieldSchema : FieldSchema, values : List<string>, 
                                   properties : ClauseProperties) = 
        if values.Count = 0 then 
            // Check if there is a configured behaviour for the missing value
            match properties.MatchRule with
            | ClauseMatchRule.All -> 
                getMatchAllDocsQuery()
                |> Some
                |> Ok
            | ClauseMatchRule.None -> 
                getMatchNoDocsQuery()
                |> Some
                |> Ok
            | ClauseMatchRule.FieldDefault -> 
                values.Add(fieldSchema.FieldType.DefaultStringValue)
                None |> Ok
            | ClauseMatchRule.UseDefault -> 
                values.Add(properties.DefaultValue.Value)
                None |> Ok
            | _ -> fail <| MissingVariableValue(fieldName)
        else None |> Ok
    
    /// Generate the leaf node clause for a given Clause predicate 
    let getClause (funcName, fieldName, parameters : FunctionParameter list) (searchQuery : SearchQuery) 
        (baggage : SearchBaggage) = 
        maybe { 
            let! fieldSchema = baggage.Fields |> getFieldSchema fieldName
            let! func = baggage.QueryFunctions |> keyExists2 (funcName, queryNotFound)
            let properties = ClauseProperties.Create(parameters)
            let tokens = stringListPool.Get()
            for p in parameters do
                match p with
                | Constant(c) -> fieldSchema |> FieldSchema.getTokens (c, tokens)
                | Variable(v) -> 
                    match searchQuery.Variables.TryGetValue <| v.ToLower() with
                    | true, value -> 
                        if isNotBlank value then fieldSchema |> FieldSchema.getTokens (value, tokens)
                    | _ -> ()
                | _ -> ()
            // We can bypass main query if we don't have any tokens to search
            let! byPassMainQuery = byPassMainQueryGeneration (fieldName, fieldSchema, tokens, properties)
            match byPassMainQuery with
            | Some(q) -> 
                // Make sure to return the item to the pool
                stringListPool.Return(tokens)
                return q
            | None -> 
                let mutable q = func.GetQuery(fieldSchema, tokens, properties)
                // It is safe to return the item to the pool as we have used
                // it in query generation.
                stringListPool.Return(tokens)
                match q with
                | Ok(q') -> 
                    let mutable q'' = q'
                    if properties.Boost.IsSome then q'' <- getBoostQuery (q', properties.Boost.Value)
                    if properties.ConstantScore.IsSome then 
                        q'' <- getConstantScoreQuery (q'', properties.ConstantScore.Value)
                    return q''
                | _ -> return! q
        }
    
    let rec generateQuery (predicate : Predicate) (searchQuery : SearchQuery) (baggage : SearchBaggage) = 
        maybe { 
            match predicate with
            | NotPredicate(pr) -> 
                let! notQuery = generateQuery pr searchQuery baggage
                return getBooleanQuery()
                       |> addMustNotClause notQuery
                       |> addMatchAllClause :> Query
            | Clause(funcName, fieldName, parameters) -> 
                return! getClause (funcName, fieldName, parameters) searchQuery baggage
            | OrPredidate(lhs, rhs) -> 
                let! lhsQuery = generateQuery lhs searchQuery baggage
                let! rhsQuery = generateQuery rhs searchQuery baggage
                return getBooleanQuery()
                       |> addShouldClause lhsQuery
                       |> addShouldClause rhsQuery :> Query
            | AndPredidate(lhs, rhs) -> 
                let! lhsQuery = generateQuery lhs searchQuery baggage
                let! rhsQuery = generateQuery rhs searchQuery baggage
                return getBooleanQuery()
                       |> addMustClause lhsQuery
                       |> addMustClause rhsQuery :> Query
        }